package net.emilsg.clutter.entity.client.animation;// Save this class in your mod and generate all required imports

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;


public class CrabAnimations {

	public static final Animation CRAB_WALKING = Animation.Builder.create(3.7083435f).looping()
			.addBoneAnimation("LeftLegs",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.6766665f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.9583435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.25f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.5416765f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("LeftLegs",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.125f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.2916765f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.6766665f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.9583435f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.5416765f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("RightLegs",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.875f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.8343335f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.125f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.4167665f, AnimationHelper.createTranslationalVector(-0.25f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(-0.5f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("RightLegs",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.875f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.8343335f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.125f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.4167665f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.7083435f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyes",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.875f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.8343335f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.125f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.4167665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Claws",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.875f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.8343335f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.125f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.4167665f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Claws",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.6766666f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.875f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.1676665f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.8343335f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.125f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.4167665f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.7083435f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("MainBody",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.875f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.8343335f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.125f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.4167665f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3.7083435f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation ANIMATION = Animation.Builder.create(0f).build();
}