package net.emilsg.clutter.entity.client.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class MossbloomAnimations {

    public static final Animation MOSSBLOOM_EARS_DROP = Animation.Builder.create(0.5f)
            .addBoneAnimation("le",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 40f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("re",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -40f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation MOSSBLOOM_WAG_TAIL = Animation.Builder.create(1f)
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, -17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation MOSSBLOOM_LE_DROP = Animation.Builder.create(0.5f)
            .addBoneAnimation("le",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 40f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation MOSSBLOOM_RE_DROP = Animation.Builder.create(0.5f)
            .addBoneAnimation("re",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -40f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation MOSSBLOOM_IDLE = Animation.Builder.create(0f).build();
    public static final Animation MOSSBLOOM_WALK = Animation.Builder.create(1f).looping()
            .addBoneAnimation("fl",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("fr",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("bl",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("br",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("neck",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation MOSSBLOOM_SHAKE_HEAD = Animation.Builder.create(3f)
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(0f, -0.17f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, -0.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, -0.48f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, AnimationHelper.createTranslationalVector(0f, -0.45f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, AnimationHelper.createTranslationalVector(0f, -0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, -0.38f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -0.36f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, -0.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, AnimationHelper.createTranslationalVector(0f, -0.31f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.29f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -0.26f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createTranslationalVector(0f, -0.24f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, AnimationHelper.createTranslationalVector(0f, -0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, AnimationHelper.createTranslationalVector(0f, -0.17f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, AnimationHelper.createTranslationalVector(0f, -0.14f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, AnimationHelper.createTranslationalVector(0f, -0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.834333f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, AnimationHelper.createTranslationalVector(0f, -0.07f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416763f, AnimationHelper.createTranslationalVector(0f, -0.17f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.083433f, AnimationHelper.createTranslationalVector(0f, -0.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676665f, AnimationHelper.createTranslationalVector(0f, -0.48f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(0f, -0.45f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0f, -0.43f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, -0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433335f, AnimationHelper.createTranslationalVector(0f, -0.38f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3750000000000002f, AnimationHelper.createTranslationalVector(0f, -0.36f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.416767f, AnimationHelper.createTranslationalVector(0f, -0.33f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583437f, AnimationHelper.createTranslationalVector(0f, -0.31f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5000000000000004f, AnimationHelper.createTranslationalVector(0f, -0.29f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416772f, AnimationHelper.createTranslationalVector(0f, -0.26f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.583434f, AnimationHelper.createTranslationalVector(0f, -0.24f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6250000000000007f, AnimationHelper.createTranslationalVector(0f, -0.21f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766674f, AnimationHelper.createTranslationalVector(0f, -0.19f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7083441f, AnimationHelper.createTranslationalVector(0f, -0.17f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7500000000000009f, AnimationHelper.createTranslationalVector(0f, -0.14f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7916776f, AnimationHelper.createTranslationalVector(0f, -0.12f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343344f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875000000000001f, AnimationHelper.createTranslationalVector(0f, -0.07f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167679f, AnimationHelper.createTranslationalVector(0f, -0.05f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583446f, AnimationHelper.createTranslationalVector(0f, -0.02f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("torso",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createRotationalVector(1.67f, 0f, 1.67f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(3.33f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(5f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, AnimationHelper.createRotationalVector(5f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(5f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(4f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(3f, 0f, 3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(2f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, AnimationHelper.createRotationalVector(1f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.834333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416763f, AnimationHelper.createRotationalVector(1.67f, 0f, 1.67f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.083433f, AnimationHelper.createRotationalVector(3.33f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(5f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676665f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(5f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(5f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433335f, AnimationHelper.createRotationalVector(4f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3750000000000002f, AnimationHelper.createRotationalVector(3f, 0f, 3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.416767f, AnimationHelper.createRotationalVector(2f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583437f, AnimationHelper.createRotationalVector(1f, 0f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416772f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.583434f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6250000000000007f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766674f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7083441f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7500000000000009f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7916776f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343344f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875000000000001f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167679f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583446f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.041678f, AnimationHelper.createRotationalVector(1.67f, 0f, 1.67f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834344f, AnimationHelper.createRotationalVector(3.33f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createRotationalVector(5f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676674f, AnimationHelper.createRotationalVector(3.75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.208344f, AnimationHelper.createRotationalVector(2.5f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2500000000000004f, AnimationHelper.createRotationalVector(1.25f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createRotationalVector(-0.13f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createRotationalVector(-0.23f, 0f, 4.61f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(-0.3f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.458343f, AnimationHelper.createRotationalVector(-0.34f, 0f, -4.06f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4999999999999996f, AnimationHelper.createRotationalVector(-0.37f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.541676f, AnimationHelper.createRotationalVector(-0.37f, 0f, 3.4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834326f, AnimationHelper.createRotationalVector(-0.36f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.624999999999999f, AnimationHelper.createRotationalVector(-0.33f, 0f, -2.68f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6766656f, AnimationHelper.createRotationalVector(-0.29f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.708342f, AnimationHelper.createRotationalVector(-0.25f, 0f, 1.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7499999999999987f, AnimationHelper.createRotationalVector(-0.2f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.791675f, AnimationHelper.createRotationalVector(-0.15f, 0f, -1.26f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8343317f, AnimationHelper.createRotationalVector(-0.11f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8749999999999982f, AnimationHelper.createRotationalVector(-0.06f, 0f, 0.65f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9167647f, AnimationHelper.createRotationalVector(-0.03f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9583413f, AnimationHelper.createRotationalVector(-0.01f, 0f, -0.17f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("neck",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createRotationalVector(7.41f, 0f, 1.48f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(17.59f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(25f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(27.34f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, AnimationHelper.createRotationalVector(28.13f, 0f, 5.63f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, AnimationHelper.createRotationalVector(27.34f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(25f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(21.2f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(15.6f, 0f, 3.12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(9.4f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, AnimationHelper.createRotationalVector(3.8f, 0f, -0.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(-0.95f, 0f, -0.19f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, AnimationHelper.createRotationalVector(-1.74f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, AnimationHelper.createRotationalVector(-2.34f, 0f, 0.47f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, AnimationHelper.createRotationalVector(-2.78f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, AnimationHelper.createRotationalVector(-3.04f, 0f, -0.61f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, AnimationHelper.createRotationalVector(-3.12f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, AnimationHelper.createRotationalVector(-3.04f, 0f, 0.61f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.834333f, AnimationHelper.createRotationalVector(-2.78f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, AnimationHelper.createRotationalVector(-2.34f, 0f, -0.47f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, AnimationHelper.createRotationalVector(-1.74f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, AnimationHelper.createRotationalVector(-0.95f, 0f, 0.19f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416763f, AnimationHelper.createRotationalVector(7.41f, 0f, 1.48f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.083433f, AnimationHelper.createRotationalVector(17.59f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(25f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676665f, AnimationHelper.createRotationalVector(27.34f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(28.13f, 0f, 5.63f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(27.34f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(25f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433335f, AnimationHelper.createRotationalVector(21.2f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3750000000000002f, AnimationHelper.createRotationalVector(15.6f, 0f, 3.12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.416767f, AnimationHelper.createRotationalVector(9.4f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583437f, AnimationHelper.createRotationalVector(3.8f, 0f, -0.76f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416772f, AnimationHelper.createRotationalVector(-0.88f, 0f, -0.21f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.583434f, AnimationHelper.createRotationalVector(-1.45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6250000000000007f, AnimationHelper.createRotationalVector(-1.76f, 0f, 0.59f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766674f, AnimationHelper.createRotationalVector(-1.85f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7083441f, AnimationHelper.createRotationalVector(-1.77f, 0f, -0.86f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7500000000000009f, AnimationHelper.createRotationalVector(-1.56f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.7916776f, AnimationHelper.createRotationalVector(-1.27f, 0f, 0.96f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343344f, AnimationHelper.createRotationalVector(-0.93f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875000000000001f, AnimationHelper.createRotationalVector(-0.59f, 0f, -0.82f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167679f, AnimationHelper.createRotationalVector(-0.29f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583446f, AnimationHelper.createRotationalVector(-0.08f, 0f, 0.37f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.041678f, AnimationHelper.createRotationalVector(0f, 0f, 2.96f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834344f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676674f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.208344f, AnimationHelper.createRotationalVector(0f, 0f, 11.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2500000000000004f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createRotationalVector(0f, 0f, 9.22f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.458343f, AnimationHelper.createRotationalVector(0f, 0f, -8.12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4999999999999996f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.541676f, AnimationHelper.createRotationalVector(0f, 0f, 6.81f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834326f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.624999999999999f, AnimationHelper.createRotationalVector(0f, 0f, -5.37f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.6766656f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.708342f, AnimationHelper.createRotationalVector(0f, 0f, 3.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.7499999999999987f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.791675f, AnimationHelper.createRotationalVector(0f, 0f, -2.51f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8343317f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.8749999999999982f, AnimationHelper.createRotationalVector(0f, 0f, 1.29f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9167647f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.9583413f, AnimationHelper.createRotationalVector(0f, 0f, -0.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
}
