package net.emilsg.clutter.block;

import net.emilsg.clutter.item.ModItems;
import net.emilsg.clutter.util.ModItemTags;
import net.emilsg.clutter.util.RegistryType;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.registry.tag.ItemTags;
import net.minecraft.registry.tag.TagKey;

import java.lang.reflect.RecordComponent;
import java.util.ArrayList;
import java.util.List;

public record ClutterWoodType(RegistryType registryType, Block sapling, Block leaves, Block log, Block wood, Block strippedLog, Block strippedWood, Block planks, Block stairs, Block slab, Block fence, Block fenceGate, Block button, Block pressurePlate, Block mosaic, Block mosaicStairs, Block mosaicSlab, Block door, Block trapdoor, Block table, Block strippedTable, Block chair, Block strippedChair, Block wallCupboard, Block cupboard, Block bench, Block strippedBench, Block shelf, Block trellis, Block shortBench, Block wallBookshelf, Block windowSill, Item signItem, Block signBlock, Block wallSignBlock, Item hangingSignItem, Block hangingSignBlock, Block hangingWallSignBlock, TagKey<Item> logTag) {

    public static final ClutterWoodType REDWOOD = new ClutterWoodType(RegistryType.MODDED, ModBlocks.REDWOOD_SAPLING, ModBlocks.REDWOOD_LEAVES, ModBlocks.REDWOOD_LOG, ModBlocks.REDWOOD_WOOD, ModBlocks.STRIPPED_REDWOOD_LOG, ModBlocks.STRIPPED_REDWOOD_WOOD, ModBlocks.REDWOOD_PLANKS, ModBlocks.REDWOOD_STAIRS, ModBlocks.REDWOOD_SLAB, ModBlocks.REDWOOD_FENCE, ModBlocks.REDWOOD_FENCE_GATE, ModBlocks.REDWOOD_BUTTON, ModBlocks.REDWOOD_PRESSURE_PLATE, ModBlocks.REDWOOD_MOSAIC, ModBlocks.REDWOOD_MOSAIC_STAIRS, ModBlocks.REDWOOD_MOSAIC_SLAB, ModBlocks.REDWOOD_DOOR, ModBlocks.REDWOOD_TRAPDOOR, ModBlocks.REDWOOD_TABLE, ModBlocks.STRIPPED_REDWOOD_TABLE, ModBlocks.REDWOOD_CHAIR, ModBlocks.STRIPPED_REDWOOD_CHAIR, ModBlocks.REDWOOD_WALL_CUPBOARD, ModBlocks.REDWOOD_CUPBOARD, ModBlocks.REDWOOD_BENCH, ModBlocks.STRIPPED_REDWOOD_BENCH, ModBlocks.REDWOOD_SHELF, ModBlocks.REDWOOD_TRELLIS, ModBlocks.REDWOOD_SHORT_BENCH, ModBlocks.REDWOOD_WALL_BOOKSHELF, ModBlocks.REDWOOD_WINDOW_SILL, ModItems.REDWOOD_SIGN, ModBlocks.REDWOOD_SIGN, ModBlocks.REDWOOD_WALL_SIGN, ModItems.REDWOOD_HANGING_SIGN, ModBlocks.REDWOOD_HANGING_SIGN, ModBlocks.REDWOOD_HANGING_WALL_SIGN, ModItemTags.REDWOOD_LOGS);
    public static final ClutterWoodType OAK = new ClutterWoodType(RegistryType.VANILLA, Blocks.OAK_SAPLING, Blocks.OAK_LEAVES, Blocks.OAK_LOG, Blocks.OAK_WOOD, Blocks.STRIPPED_OAK_LOG, Blocks.STRIPPED_OAK_WOOD, Blocks.OAK_PLANKS, Blocks.OAK_STAIRS, Blocks.OAK_SLAB, Blocks.OAK_FENCE, Blocks.OAK_FENCE_GATE, Blocks.OAK_BUTTON, Blocks.OAK_PRESSURE_PLATE, ModBlocks.OAK_MOSAIC, ModBlocks.OAK_MOSAIC_STAIRS, ModBlocks.OAK_MOSAIC_SLAB, Blocks.OAK_DOOR, Blocks.OAK_TRAPDOOR, ModBlocks.OAK_TABLE, ModBlocks.STRIPPED_OAK_TABLE, ModBlocks.OAK_CHAIR, ModBlocks.STRIPPED_OAK_CHAIR, ModBlocks.OAK_WALL_CUPBOARD, ModBlocks.OAK_CUPBOARD, ModBlocks.OAK_BENCH, ModBlocks.STRIPPED_OAK_BENCH, ModBlocks.OAK_SHELF, ModBlocks.OAK_TRELLIS, ModBlocks.OAK_SHORT_BENCH, ModBlocks.OAK_WALL_BOOKSHELF, ModBlocks.OAK_WINDOW_SILL, Items.OAK_SIGN, Blocks.OAK_SIGN, Blocks.OAK_WALL_SIGN, Items.OAK_HANGING_SIGN, Blocks.OAK_HANGING_SIGN, Blocks.OAK_WALL_HANGING_SIGN, ItemTags.OAK_LOGS);
    public static final ClutterWoodType BIRCH = new ClutterWoodType(RegistryType.VANILLA, Blocks.BIRCH_SAPLING, Blocks.BIRCH_LEAVES, Blocks.BIRCH_LOG, Blocks.BIRCH_WOOD, Blocks.STRIPPED_BIRCH_LOG, Blocks.STRIPPED_BIRCH_WOOD, Blocks.BIRCH_PLANKS, Blocks.BIRCH_STAIRS, Blocks.BIRCH_SLAB, Blocks.BIRCH_FENCE, Blocks.BIRCH_FENCE_GATE, Blocks.BIRCH_BUTTON, Blocks.BIRCH_PRESSURE_PLATE, ModBlocks.BIRCH_MOSAIC, ModBlocks.BIRCH_MOSAIC_STAIRS, ModBlocks.BIRCH_MOSAIC_SLAB, Blocks.BIRCH_DOOR, Blocks.BIRCH_TRAPDOOR, ModBlocks.BIRCH_TABLE, ModBlocks.STRIPPED_BIRCH_TABLE, ModBlocks.BIRCH_CHAIR, ModBlocks.STRIPPED_BIRCH_CHAIR, ModBlocks.BIRCH_WALL_CUPBOARD, ModBlocks.BIRCH_CUPBOARD, ModBlocks.BIRCH_BENCH, ModBlocks.STRIPPED_BIRCH_BENCH, ModBlocks.BIRCH_SHELF, ModBlocks.BIRCH_TRELLIS, ModBlocks.BIRCH_SHORT_BENCH, ModBlocks.BIRCH_WALL_BOOKSHELF, ModBlocks.BIRCH_WINDOW_SILL, Items.BIRCH_SIGN, Blocks.BIRCH_SIGN, Blocks.BIRCH_WALL_SIGN, Items.BIRCH_HANGING_SIGN, Blocks.BIRCH_HANGING_SIGN, Blocks.BIRCH_WALL_HANGING_SIGN, ItemTags.BIRCH_LOGS);
    public static final ClutterWoodType JUNGLE = new ClutterWoodType(RegistryType.VANILLA, Blocks.JUNGLE_SAPLING, Blocks.JUNGLE_LEAVES, Blocks.JUNGLE_LOG, Blocks.JUNGLE_WOOD, Blocks.STRIPPED_JUNGLE_LOG, Blocks.STRIPPED_JUNGLE_WOOD, Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_STAIRS, Blocks.JUNGLE_SLAB, Blocks.JUNGLE_FENCE, Blocks.JUNGLE_FENCE_GATE, Blocks.JUNGLE_BUTTON, Blocks.JUNGLE_PRESSURE_PLATE, ModBlocks.JUNGLE_MOSAIC, ModBlocks.JUNGLE_MOSAIC_STAIRS, ModBlocks.JUNGLE_MOSAIC_SLAB, Blocks.JUNGLE_DOOR, Blocks.JUNGLE_TRAPDOOR, ModBlocks.JUNGLE_TABLE, ModBlocks.STRIPPED_JUNGLE_TABLE, ModBlocks.JUNGLE_CHAIR, ModBlocks.STRIPPED_JUNGLE_CHAIR, ModBlocks.JUNGLE_WALL_CUPBOARD, ModBlocks.JUNGLE_CUPBOARD, ModBlocks.JUNGLE_BENCH, ModBlocks.STRIPPED_JUNGLE_BENCH, ModBlocks.JUNGLE_SHELF, ModBlocks.JUNGLE_TRELLIS, ModBlocks.JUNGLE_SHORT_BENCH, ModBlocks.JUNGLE_WALL_BOOKSHELF, ModBlocks.JUNGLE_WINDOW_SILL, Items.JUNGLE_SIGN, Blocks.JUNGLE_SIGN, Blocks.JUNGLE_WALL_SIGN, Items.JUNGLE_HANGING_SIGN, Blocks.JUNGLE_HANGING_SIGN, Blocks.JUNGLE_WALL_HANGING_SIGN, ItemTags.JUNGLE_LOGS);
    public static final ClutterWoodType ACACIA = new ClutterWoodType(RegistryType.VANILLA, Blocks.ACACIA_SAPLING, Blocks.ACACIA_LEAVES, Blocks.ACACIA_LOG, Blocks.ACACIA_WOOD, Blocks.STRIPPED_ACACIA_LOG, Blocks.STRIPPED_ACACIA_WOOD, Blocks.ACACIA_PLANKS, Blocks.ACACIA_STAIRS, Blocks.ACACIA_SLAB, Blocks.ACACIA_FENCE, Blocks.ACACIA_FENCE_GATE, Blocks.ACACIA_BUTTON, Blocks.ACACIA_PRESSURE_PLATE, ModBlocks.ACACIA_MOSAIC, ModBlocks.ACACIA_MOSAIC_STAIRS, ModBlocks.ACACIA_MOSAIC_SLAB, Blocks.ACACIA_DOOR, Blocks.ACACIA_TRAPDOOR, ModBlocks.ACACIA_TABLE, ModBlocks.STRIPPED_ACACIA_TABLE, ModBlocks.ACACIA_CHAIR, ModBlocks.STRIPPED_ACACIA_CHAIR, ModBlocks.ACACIA_WALL_CUPBOARD, ModBlocks.ACACIA_CUPBOARD, ModBlocks.ACACIA_BENCH, ModBlocks.STRIPPED_ACACIA_BENCH, ModBlocks.ACACIA_SHELF, ModBlocks.ACACIA_TRELLIS, ModBlocks.ACACIA_SHORT_BENCH, ModBlocks.ACACIA_WALL_BOOKSHELF, ModBlocks.ACACIA_WINDOW_SILL, Items.ACACIA_SIGN, Blocks.ACACIA_SIGN, Blocks.ACACIA_WALL_SIGN, Items.ACACIA_HANGING_SIGN, Blocks.ACACIA_HANGING_SIGN, Blocks.ACACIA_WALL_HANGING_SIGN, ItemTags.ACACIA_LOGS);
    public static final ClutterWoodType SPRUCE = new ClutterWoodType(RegistryType.VANILLA, Blocks.SPRUCE_SAPLING, Blocks.SPRUCE_LEAVES, Blocks.SPRUCE_LOG, Blocks.SPRUCE_WOOD, Blocks.STRIPPED_SPRUCE_LOG, Blocks.STRIPPED_SPRUCE_WOOD, Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_STAIRS, Blocks.SPRUCE_SLAB, Blocks.SPRUCE_FENCE, Blocks.SPRUCE_FENCE_GATE, Blocks.SPRUCE_BUTTON, Blocks.SPRUCE_PRESSURE_PLATE, ModBlocks.SPRUCE_MOSAIC, ModBlocks.SPRUCE_MOSAIC_STAIRS, ModBlocks.SPRUCE_MOSAIC_SLAB, Blocks.SPRUCE_DOOR, Blocks.SPRUCE_TRAPDOOR, ModBlocks.SPRUCE_TABLE, ModBlocks.STRIPPED_SPRUCE_TABLE, ModBlocks.SPRUCE_CHAIR, ModBlocks.STRIPPED_SPRUCE_CHAIR, ModBlocks.SPRUCE_WALL_CUPBOARD, ModBlocks.SPRUCE_CUPBOARD, ModBlocks.SPRUCE_BENCH, ModBlocks.STRIPPED_SPRUCE_BENCH, ModBlocks.SPRUCE_SHELF, ModBlocks.SPRUCE_TRELLIS, ModBlocks.SPRUCE_SHORT_BENCH, ModBlocks.SPRUCE_WALL_BOOKSHELF, ModBlocks.SPRUCE_WINDOW_SILL, Items.SPRUCE_SIGN, Blocks.SPRUCE_SIGN, Blocks.SPRUCE_WALL_SIGN, Items.SPRUCE_HANGING_SIGN, Blocks.SPRUCE_HANGING_SIGN, Blocks.SPRUCE_WALL_HANGING_SIGN, ItemTags.SPRUCE_LOGS);
    public static final ClutterWoodType DARK_OAK = new ClutterWoodType(RegistryType.VANILLA, Blocks.DARK_OAK_SAPLING, Blocks.DARK_OAK_LEAVES, Blocks.DARK_OAK_LOG, Blocks.DARK_OAK_WOOD, Blocks.STRIPPED_DARK_OAK_LOG, Blocks.STRIPPED_DARK_OAK_WOOD, Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_STAIRS, Blocks.DARK_OAK_SLAB, Blocks.DARK_OAK_FENCE, Blocks.DARK_OAK_FENCE_GATE, Blocks.DARK_OAK_BUTTON, Blocks.DARK_OAK_PRESSURE_PLATE, ModBlocks.DARK_OAK_MOSAIC, ModBlocks.DARK_OAK_MOSAIC_STAIRS, ModBlocks.DARK_OAK_MOSAIC_SLAB, Blocks.DARK_OAK_DOOR, Blocks.DARK_OAK_TRAPDOOR, ModBlocks.DARK_OAK_TABLE, ModBlocks.STRIPPED_DARK_OAK_TABLE, ModBlocks.DARK_OAK_CHAIR, ModBlocks.STRIPPED_DARK_OAK_CHAIR, ModBlocks.DARK_OAK_WALL_CUPBOARD, ModBlocks.DARK_OAK_CUPBOARD, ModBlocks.DARK_OAK_BENCH, ModBlocks.STRIPPED_DARK_OAK_BENCH, ModBlocks.DARK_OAK_SHELF, ModBlocks.DARK_OAK_TRELLIS, ModBlocks.DARK_OAK_SHORT_BENCH, ModBlocks.DARK_OAK_WALL_BOOKSHELF, ModBlocks.DARK_OAK_WINDOW_SILL, Items.DARK_OAK_SIGN, Blocks.DARK_OAK_SIGN, Blocks.DARK_OAK_WALL_SIGN, Items.DARK_OAK_HANGING_SIGN, Blocks.DARK_OAK_HANGING_SIGN, Blocks.DARK_OAK_WALL_HANGING_SIGN, ItemTags.DARK_OAK_LOGS);
    public static final ClutterWoodType MANGROVE = new ClutterWoodType(RegistryType.VANILLA, Blocks.MANGROVE_PROPAGULE, Blocks.MANGROVE_LEAVES, Blocks.MANGROVE_LOG, Blocks.MANGROVE_WOOD, Blocks.STRIPPED_MANGROVE_LOG, Blocks.STRIPPED_MANGROVE_WOOD, Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_STAIRS, Blocks.MANGROVE_SLAB, Blocks.MANGROVE_FENCE, Blocks.MANGROVE_FENCE_GATE, Blocks.MANGROVE_BUTTON, Blocks.MANGROVE_PRESSURE_PLATE, ModBlocks.MANGROVE_MOSAIC, ModBlocks.MANGROVE_MOSAIC_STAIRS, ModBlocks.MANGROVE_MOSAIC_SLAB, Blocks.MANGROVE_DOOR, Blocks.MANGROVE_TRAPDOOR, ModBlocks.MANGROVE_TABLE, ModBlocks.STRIPPED_MANGROVE_TABLE, ModBlocks.MANGROVE_CHAIR, ModBlocks.STRIPPED_MANGROVE_CHAIR, ModBlocks.MANGROVE_WALL_CUPBOARD, ModBlocks.MANGROVE_CUPBOARD, ModBlocks.MANGROVE_BENCH, ModBlocks.STRIPPED_MANGROVE_BENCH, ModBlocks.MANGROVE_SHELF, ModBlocks.MANGROVE_TRELLIS, ModBlocks.MANGROVE_SHORT_BENCH, ModBlocks.MANGROVE_WALL_BOOKSHELF, ModBlocks.MANGROVE_WINDOW_SILL, Items.MANGROVE_SIGN, Blocks.MANGROVE_SIGN, Blocks.MANGROVE_WALL_SIGN, Items.MANGROVE_HANGING_SIGN, Blocks.MANGROVE_HANGING_SIGN, Blocks.MANGROVE_WALL_HANGING_SIGN, ItemTags.MANGROVE_LOGS);
    public static final ClutterWoodType CRIMSON = new ClutterWoodType(RegistryType.VANILLA, Blocks.CRIMSON_FUNGUS, Blocks.NETHER_WART_BLOCK, Blocks.CRIMSON_STEM, Blocks.CRIMSON_HYPHAE, Blocks.STRIPPED_CRIMSON_STEM, Blocks.STRIPPED_CRIMSON_HYPHAE, Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_STAIRS, Blocks.CRIMSON_SLAB, Blocks.CRIMSON_FENCE, Blocks.CRIMSON_FENCE_GATE, Blocks.CRIMSON_BUTTON, Blocks.CRIMSON_PRESSURE_PLATE, ModBlocks.CRIMSON_MOSAIC, ModBlocks.CRIMSON_MOSAIC_STAIRS, ModBlocks.CRIMSON_MOSAIC_SLAB, Blocks.CRIMSON_DOOR, Blocks.CRIMSON_TRAPDOOR, ModBlocks.CRIMSON_TABLE, ModBlocks.STRIPPED_CRIMSON_TABLE, ModBlocks.CRIMSON_CHAIR, ModBlocks.STRIPPED_CRIMSON_CHAIR, ModBlocks.CRIMSON_WALL_CUPBOARD, ModBlocks.CRIMSON_CUPBOARD, ModBlocks.CRIMSON_BENCH, ModBlocks.STRIPPED_CRIMSON_BENCH, ModBlocks.CRIMSON_SHELF, ModBlocks.CRIMSON_TRELLIS, ModBlocks.CRIMSON_SHORT_BENCH, ModBlocks.CRIMSON_WALL_BOOKSHELF, ModBlocks.CRIMSON_WINDOW_SILL, Items.CRIMSON_SIGN, Blocks.CRIMSON_SIGN, Blocks.CRIMSON_WALL_SIGN, Items.CRIMSON_HANGING_SIGN, Blocks.CRIMSON_HANGING_SIGN, Blocks.CRIMSON_WALL_HANGING_SIGN, ItemTags.CRIMSON_STEMS);
    public static final ClutterWoodType WARPED = new ClutterWoodType(RegistryType.VANILLA, Blocks.WARPED_FUNGUS, Blocks.NETHER_WART_BLOCK, Blocks.WARPED_STEM, Blocks.WARPED_HYPHAE, Blocks.STRIPPED_WARPED_STEM, Blocks.STRIPPED_WARPED_HYPHAE, Blocks.WARPED_PLANKS, Blocks.WARPED_STAIRS, Blocks.WARPED_SLAB, Blocks.WARPED_FENCE, Blocks.WARPED_FENCE_GATE, Blocks.WARPED_BUTTON, Blocks.WARPED_PRESSURE_PLATE, ModBlocks.WARPED_MOSAIC, ModBlocks.WARPED_MOSAIC_STAIRS, ModBlocks.WARPED_MOSAIC_SLAB, Blocks.WARPED_DOOR, Blocks.WARPED_TRAPDOOR, ModBlocks.WARPED_TABLE, ModBlocks.STRIPPED_WARPED_TABLE, ModBlocks.WARPED_CHAIR, ModBlocks.STRIPPED_WARPED_CHAIR, ModBlocks.WARPED_WALL_CUPBOARD, ModBlocks.WARPED_CUPBOARD, ModBlocks.WARPED_BENCH, ModBlocks.STRIPPED_WARPED_BENCH, ModBlocks.WARPED_SHELF, ModBlocks.WARPED_TRELLIS, ModBlocks.WARPED_SHORT_BENCH, ModBlocks.WARPED_WALL_BOOKSHELF, ModBlocks.WARPED_WINDOW_SILL, Items.WARPED_SIGN, Blocks.WARPED_SIGN, Blocks.WARPED_WALL_SIGN, Items.WARPED_HANGING_SIGN, Blocks.WARPED_HANGING_SIGN, Blocks.WARPED_WALL_HANGING_SIGN, ItemTags.WARPED_STEMS);
    public static final ClutterWoodType CHERRY = new ClutterWoodType(RegistryType.VANILLA, Blocks.CHERRY_SAPLING, Blocks.CHERRY_LEAVES, Blocks.CHERRY_LOG, Blocks.CHERRY_WOOD, Blocks.STRIPPED_CHERRY_LOG, Blocks.STRIPPED_CHERRY_WOOD, Blocks.CHERRY_PLANKS, Blocks.CHERRY_STAIRS, Blocks.CHERRY_SLAB, Blocks.CHERRY_FENCE, Blocks.CHERRY_FENCE_GATE, Blocks.CHERRY_BUTTON, Blocks.CHERRY_PRESSURE_PLATE, ModBlocks.CHERRY_MOSAIC, ModBlocks.CHERRY_MOSAIC_STAIRS, ModBlocks.CHERRY_MOSAIC_SLAB, Blocks.CHERRY_DOOR, Blocks.CHERRY_TRAPDOOR, ModBlocks.CHERRY_TABLE, ModBlocks.STRIPPED_CHERRY_TABLE, ModBlocks.CHERRY_CHAIR, ModBlocks.STRIPPED_CHERRY_CHAIR, ModBlocks.CHERRY_WALL_CUPBOARD, ModBlocks.CHERRY_CUPBOARD, ModBlocks.CHERRY_BENCH, ModBlocks.STRIPPED_CHERRY_BENCH, ModBlocks.CHERRY_SHELF, ModBlocks.CHERRY_TRELLIS, ModBlocks.CHERRY_SHORT_BENCH, ModBlocks.CHERRY_WALL_BOOKSHELF, ModBlocks.CHERRY_WINDOW_SILL, Items.CHERRY_SIGN, Blocks.CHERRY_SIGN, Blocks.CHERRY_WALL_SIGN, Items.CHERRY_HANGING_SIGN, Blocks.CHERRY_HANGING_SIGN, Blocks.CHERRY_WALL_HANGING_SIGN, ItemTags.CHERRY_LOGS);
    public static final ClutterWoodType BAMBOO = new ClutterWoodType(RegistryType.VANILLA, Blocks.BAMBOO_SAPLING, null, Blocks.BAMBOO_BLOCK, null, Blocks.STRIPPED_BAMBOO_BLOCK, null, Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_STAIRS, Blocks.BAMBOO_SLAB, Blocks.BAMBOO_FENCE, Blocks.BAMBOO_FENCE_GATE, Blocks.BAMBOO_BUTTON, Blocks.BAMBOO_PRESSURE_PLATE, Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_MOSAIC_STAIRS, Blocks.BAMBOO_MOSAIC_SLAB, Blocks.BAMBOO_DOOR, Blocks.BAMBOO_TRAPDOOR, ModBlocks.BAMBOO_TABLE, null, ModBlocks.BAMBOO_CHAIR, null, ModBlocks.BAMBOO_WALL_CUPBOARD, ModBlocks.BAMBOO_CUPBOARD, ModBlocks.BAMBOO_BENCH, null, ModBlocks.BAMBOO_SHELF, ModBlocks.BAMBOO_TRELLIS, ModBlocks.BAMBOO_SHORT_BENCH, ModBlocks.BAMBOO_WALL_BOOKSHELF, ModBlocks.BAMBOO_WINDOW_SILL, Items.BAMBOO_SIGN, Blocks.BAMBOO_SIGN, Blocks.BAMBOO_WALL_SIGN, Items.BAMBOO_HANGING_SIGN, Blocks.BAMBOO_HANGING_SIGN, Blocks.BAMBOO_WALL_HANGING_SIGN, ItemTags.BAMBOO_BLOCKS);

    public static final ClutterWoodType[] CLUTTER_WOOD_TYPES = {ClutterWoodType.REDWOOD, ClutterWoodType.OAK, ClutterWoodType.BIRCH, ClutterWoodType.JUNGLE, ClutterWoodType.ACACIA, ClutterWoodType.SPRUCE, ClutterWoodType.DARK_OAK, ClutterWoodType.MANGROVE, ClutterWoodType.CRIMSON, ClutterWoodType.WARPED, ClutterWoodType.CHERRY, ClutterWoodType.BAMBOO};
    public static List<Block> CLUTTER_WOOD_BLOCKS = new ArrayList<>();

    public boolean isOf(ClutterWoodType clutterWoodType) {
        return this == clutterWoodType;
    }

    static {
        for (ClutterWoodType woodType : ClutterWoodType.CLUTTER_WOOD_TYPES) {
            Class<?> woodTypeClass = woodType.getClass();

            if (woodTypeClass.isRecord()) {
                for (RecordComponent component : woodTypeClass.getRecordComponents()) {
                    try {
                        Object value = component.getAccessor().invoke(woodType);
                        if (value instanceof Block block) {
                            CLUTTER_WOOD_BLOCKS.add(block);
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }
}
